{"name": "Вход курьера в прилоежине без логина с возваращением ошибки-", "status": "passed", "start": 1725392775445, "stop": 1725392775920, "uuid": "5f172169-63a3-4327-a9d4-4fc193796745", "historyId": "2053ef848e1609ea7585fc57d94dbf66", "testCaseId": "2053ef848e1609ea7585fc57d94dbf66", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_without_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-ECR6Q27"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}