{"name": "Создание курьера с уже существующим логином с возвращением ошибки-", "status": "passed", "start": 1725392747757, "stop": 1725392747949, "uuid": "fbc25d9a-fb32-4a6c-96bd-81b2ecf912fa", "historyId": "8fb5d821b574f7dbc547d323e09ddb11", "testCaseId": "8fb5d821b574f7dbc547d323e09ddb11", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_courier_with_duplicate_login_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-ECR6Q27"}, {"name": "thread", "value": "3304-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}